---
# tasks file for sbaerlocher.wmi_exporter

- name: 'package : include prepare arguments'
  include_tasks: _prepare_arguments.yml

- name: 'choco : install wmi exporter'
  chocolatey.chocolatey.win_chocolatey:
    name: prometheus-windows-exporter.install
    proxy_url: '{{ wmi_exporter_proxy }}'
    version: '{{ wmi_exporter_version | default(omit) }}'
    params: '{{ wmi_exporter_install_arguments | default([]) | join(" ") }}'
