---
# tasks file for sbaerlocher.wmi_exporter

- name: 'package : create download directory'
  ansible.windows.win_file:
    path: '{{ wmi_exporter_download_directory }}'
    state: directory

- name: 'package : download wmi_exporter'
  ansible.windows.win_get_url:
    url: '{{ var_url }}/{{ var_url_file }}'
    dest: '{{ wmi_exporter_download_directory }}\\wmi_exporter.msi'
    proxy_url: '{{ wmi_exporter_proxy }}'
    validate_certs: '{{ wmi_exporter_validate_certs }}'
    follow_redirects: all
  vars:
    var_url: '{{ var_url_base }}/releases/download/v{{ wmi_exporter_version }}'
    var_url_base: https://github.com/prometheus-community/windows_exporter
    var_url_file: 'windows_exporter-{{ wmi_exporter_version }}-{{ wmi_exporter_architecture }}.msi'
  when: not wmi_exporter_local_download

- name: 'package : downloading on localhost'
  block:

    - name: 'package : create temp directory (localhost)'
      tempfile:
        state: directory
      register: tmpdir_installer
      delegate_to: localhost

    - name: 'package : download wmi_exporter (localhost)'
      get_url:
        url: '{{ var_url }}/{{ var_url_file }}'
        dest: '{{ tmpdir_installer.path }}/wmi_exporter.msi'
        proxy_url: '{{ wmi_exporter_proxy }}'
        validate_certs: '{{ wmi_exporter_validate_certs }}'
      delegate_to: localhost
      register: register_wmi_exporter_local_package

    - name: 'package : copy file to remote node'
      ansible.windows.win_copy:
        src: '{{ tmpdir_installer.path }}/wmi_exporter.msi'
        dest: '{{ wmi_exporter_download_directory }}\\wmi_exporter.msi'

  always:

    - name: 'package : cleanup temp dir (localhost)'
      file:
        path: "{{ tmpdir_installer.path }}"
        state: absent
      delegate_to: localhost

  vars:
    var_url: '{{ var_url_base }}/releases/download/v{{ wmi_exporter_version }}'
    var_url_base: https://github.com/prometheus-community/windows_exporter
    var_url_file: 'windows_exporter-{{ wmi_exporter_version }}-{{ wmi_exporter_architecture }}.msi'

  when: wmi_exporter_local_download | bool

- name: 'package : include prepare arguments'
  include_tasks: _prepare_arguments.yml

- name: 'package : install wmi_exporter'
  ansible.windows.win_package:
    product_id: "{{ windows_exporter_guid }}"
    path: '{{ wmi_exporter_download_directory }}\\wmi_exporter.msi'
    chdir: '{{ wmi_exporter_download_directory }}'
    state: present
    arguments: '{{ wmi_exporter_install_arguments | default([]) | join(" ") }}'
